### PR TITLE
Feat/uni v3 ite 2

### PR DESCRIPTION
**Pull request by vic-en**

### CODE REVIEW

**Review by RC-13 — APPROVED** [review]
LGTM

**Review by CrimsonJacket — APPROVED** [review]
Considering that Gateway serves as a API interface between the client and the protocol, I can say it's pretty straightforward and I was able to setup the gateway and play around with the postman collections. I'd like to do more by examining the interactions between the client and the gateway but overall it looks good to me.

**Comment by PtrckM** [comment]
@james-hummingbot last 3 commits https://github.com/CoinAlpha/gateway-api/pull/102/commits/d3eb88dd41d373d395d58ba4eee06c4c35f4285c https://github.com/CoinAlpha/gateway-api/pull/102/commits/20e5db8f997b68dfb190215036c0aa67612077ff https://github.com/CoinAlpha/gateway-api/pull/102/commits/89190311abac6295f85fac5d329ce94c390861df causing:
 - incorrect balance
 - unable to create orders/position range
 
image
image
image

**Review by PtrckM — APPROVED** [review]
Tested on mainnet and confirmed working, run together using client PR#3651, commit b7b0586b9a7abc2c945d5af8b46eaad5792718d5

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
