### PR TITLE
Feat/gateway configuration for switching network

### PR DESCRIPTION
**Pull request by sdgoh**
* Config endpoint accept Hummingbot ethereum rpc url, ethereum chain, terra lcd url, terra chain and client id. 
* Instantiate Balancer(), Ethereum(), Terra() in route to load latest chain
* Invalidate balancer/sor module cache upon chain switch
* Moved Balancer address (Multi, Exchange Proxy, Subgraph URL), Uniswap router to protocol.json static
* Remove dependancies on .env variables for chain setting
* Load Balancer, Uniswap spenders proxy info from config file

### CODE REVIEW

**Comment by sdgoh** [comment]
@mifeng @vic-en You can test the config update endpoint using the Postman file (`test/postman/Gateway.postman_collection.json`). I'll update the client to add the ethereum chain switching based-on the global config.

**Review by mifeng — COMMENTED** [review]
@sdgoh I think the approach of copying values from the client's `conf_global.yml` file to Gateway is good. However, using `data/gateway_config.json` seems more complex than populating an `.env` file. 

Was this change primarily to enable the client to change Ethereum networks and still enable Balancer's subgraph URL to work? If so, I'm not sure that it's worth the additional complexity. Let's discuss later today.

**Comment by sdgoh** [comment]
The `conf_global.yml` allows us to switch network without restarting the Node server. It did added some complexity and requires re-instantiation of some classes. And it seems to slow down the endpoints from some observations. Due to the performance issue, I have reservations on whether it is worth the change.

**Comment by dennisocana** [comment]
@vic-en will recreate the PR with some additional updates to the code.

**Pull request closed without merging**
