### PR TITLE
(feat) standard endpoints & consolidate protocol library functions

### PR DESCRIPTION
**Pull request by sdgoh**
* merge balancer & uniswap endpoint to under /eth
* consolidate functions on balancer, uniswap swaps price lookup
* cache swap pool as class property
* replace token contract address with token symbol on request param
* add mainnet token list (1inch)
* add maxswaps, ethGasStation api, gas level param to .env

### CODE REVIEW

**Comment by sdgoh** [comment]
API Endpoints are consolidated as below:

General Ethereum API
``` 
# get ethereum-based wallet balances
/eth/balances
# get token allowance amount
/eth/allowances
# approve token allowance amount
/eth/approve
# get tx status update
/eth/poll
```

Balancer/Uniswap API
```
# initiate swappool, auto-approve allowance
eth/{protocol}/start
# lookup buy/sell price
eth/{protocol}/price
# execute buy/sell trade
eth/{protocol}/trade
```

Import Postman collection & environment file in `test/postman/v2` for latest endpoints and request params

**Comment by sdgoh** [comment]
Client PR for this feature. https://github.com/CoinAlpha/hummingbot/pull/2905.

**Comment by dennisocana** [comment]
Requesting review from @vic-en as well so he can work on the story https://github.com/CoinAlpha/hummingbot/issues/3037

**Review by vic-en — DISMISSED** [review]

**Comment by PtrckM** [comment]
- using the config1
image
- no problem on subsequent orders
image

- however using this config2
image
- resulting with `Fail with error 'UniswapV2Router: EXCESSIVE_INPUT_AMOUNT'` 
image
image

- also the `history` are incorrect on uniswap/balancer side
image

- different behavior on balancer using config3
image
image
image

-logs config1 config2 (uniswap)
[logs_doonconf.log](https://github.com/CoinAlpha/gateway-api/files/6196818/logs_doonconf.log)
[logs_uniswap.log](https://github.com/CoinAlpha/gateway-api/files/6196820/logs_uniswap.log)

-logs config3 balancer
[logs_ditomobile.log](https://github.com/CoinAlpha/gateway-api/files/6196877/logs_ditomobile.log)

**Comment by PtrckM** [comment]
- not able to run gateway, tried on different node versions v10.22.0, v10.22.1 and v10.23.1 all fails. Both mainnet and kovan fails
image

- able to run on both commit `e354cbecaac8f6da93f424f453125acf9c462244` and `658429896355eaae3e3a4a0dd3a064f9c2a06e9d` without any problems.
image

**Comment by PtrckM** [comment]
- fix issue where gateway can't start
image

- suggested `UNISWAP_ALLOWED_SLIPPAGE=1.5`
image

**Review by vic-en — APPROVED** [review]
LGTM

**Review by PtrckM — APPROVED** [review]
Tested and confirmed working by QA.

**Pull request merged**
