### PR TITLE
Feat/new gateway config

### PR DESCRIPTION
**Pull request by vic-en**
Note the list of updated commands for gateway.
`yarn run start` - To start gateway in production mode
`yarn run status` - To view active status of gateway in production mode
`yarn run logs` - To view recent logs of gateway
`yarn run stop` - To stop gateway in production
`yarn run debug`- To run gateway in debug mode

Also, users have to update the global_config.yml file on first run as usual.

### CODE REVIEW

**Comment by RC-13** [comment]
New commands have been tested and confirmed working however, we tried running the new gateway change with AMM arbitrage strategy and it fails to run when Balancer and Uniswap are used as connectors. Stuck with `market not ready` status and `no pool` on the gateway side. However, it's working fine when the gateway instance is using the master or development branch. Is this issue related to the recent change?

This test is done using KOVAN network. For terra, no issue on both mainnet and testnet.
image
image

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by PtrckM** [comment]
Docker Build
- node version needs to be updating on https://github.com/CoinAlpha/gateway-api/blob/feat/new_gateway_config/Dockerfile#L1 to v12.13.0 or 12.x. Tested and works fine on `node:12.13.0-alpine`
- `./create-gateway.sh` no longer works cause `.env` no longer used?
- gateway will start upon creation but will not run continually when using docker, editing this https://github.com/CoinAlpha/gateway-api/blob/feat/new_gateway_config/Dockerfile#L34 to `yarn run debug` mode will work 

image

**Comment by PtrckM** [comment]
Docker script `create-gateway.sh` needs updating in order to make it work on docker build. Overall works well on source build.

**Review by RC-13 — APPROVED** [review]
LGTM

**Pull request merged**
