### PR TITLE
Feat / logger to save info, warning, error to local log files

### PR DESCRIPTION
**Pull request by sdgoh**
Add logger to save info, warning, error to local log files.

### CODE REVIEW

**Comment by sdgoh** [comment]
Currently `logs/app.log` will capture the error as all info, error logs. I'll find out how to filter out error log in the `app.log`. 

Note that `development` branch has been updated to use the decimal param in the request. Please refer to the `test/postman/Gateway-Ethereum-Base.postman_collection.json` file for updated params.

**Comment by sdgoh** [comment]
# capture any info type logging
logs/app.log

# capture any error type logging
logs/error.log

# capture any unhandled exceptions
logs/rejection.log

**Review by mifeng — APPROVED** [review]
Looks good overall - a couple of questions and comments:
1. Does `app.log` contain all log messages, including info, errors, debug, etc?
2. Can you see if you can format the timestamps in same format as client? yyyy-mm-dd with 24h clock
3. If user installs via Docker, where are the log files saved?

**Comment by mifeng** [comment]
> Currently `logs/app.log` will capture all info, error logs. I'll find out how to filter out error log in the `app.log`.

I think it's good that `app.log` contains all log messages, including errors.

**Comment by RC-13** [comment]
Tested and confirmed by QA

Test summary:
- pull and run gateway branch
- create amm_arb strategy using HB (source) 
- run strategy
- review logs folder inside gateway
  ->3 files found : Ok
  -> review `app.log`:  informative output 
        = 12/25/2020, 7:12:35 PM | info |         Pools Retrieved. mainnet
        = 12/25/2020, 7:18:29 PM | error |        missing response 
  -> review `error.log` : compare error logs and error output saved on `app.log` - Ok
  -> review `rejection.log` : no error captured during test
 - delete log files and start gateway instance : files recreated - Ok

**Review by RC-13 — APPROVED** [review]

**Pull request merged**
